Models/Flavor.cs
using System.Collections.Generic;

namespace SweetCakes.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.Treats = new List<FlavorTreat>();
    }

    public int FlavorId { get; set; }
    public string FlavorName { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> Treats { get; set; }
  }
}

Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using SweetCakes.Models;

namespace SweetCakes.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly SweetCakesContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, SweetCakesContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> Create(Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      _db.Flavors.Add(flav);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlav = _db.Flavors
          .Include(flav => flav.Treats)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    public ActionResult Edit(int id)
    {
      var thisFlav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> Edit(Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      _db.Entry(flav).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    [HttpPost, ActionName("Delete")]
    [Authorize]
    public async Task<ActionResult> DeleteConfirmed(int id, Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      var thisFlav = _db.Flavors.FirstOrDefault(f => f.FlavorId == id);
      _db.Flavors.Remove(thisFlav);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    [Authorize]
    public ActionResult AddFlavor(Flavor flav, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flav.FlavorId });
      }
      _db.Entry(flav).Collection(f => f.Treats).IsModified = true;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

Controllers/TreatController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using SweetCakes.Models;

namespace SweetCakes.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetCakesContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SweetCakesContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.Flavors)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddTag(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).Collection(t => t.Flavors).IsModified = true;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // [HttpGet("/search")]
    // public ActionResult Search(string search, string searchParam)
    // {

    //   if (!string.IsNullOrEmpty(search))
    //   {
    //     if (searchParam == "Tags")
    //     {
    //       var thisTag = _db.Tags
    //       .Include(tag => tag.Recipes)
    //       .ThenInclude(join => join.Recipe)
    //       .FirstOrDefault(tag => tag.Word == search);
    //       return View(thisTag.Recipes);

    //     }
    //     else if (searchParam == "Name")
    //     {
    //       var model = from r in _db.Recipes select r;
    //       model = model.Where(r => r.Name.Contains(search));
    //       List<Recipe> matches = model.ToList();
    //       return View(matches);
    //     }
    //     else
    //     {
    //       var model = from m in _db.Recipes select m;
    //       List<Recipe> allRecipes = new List<Recipe> { };
    //       allRecipes = model.ToList();
    //       return View(allRecipes);
    //     }
    //   }
    //   else
    //   {
    //     return RedirectToAction("Index");
    //   }
    // }
    // [HttpGet("/sort")]
    // public ActionResult Sort(string sortParam)
    // {
    //   List<Recipe> model = _db.Recipes.ToList();
    //   if (sortParam == "Rating")
    //   {
    //     model = model.OrderByDescending(r => r.Rating).ToList();
    //   }
    //   else
    //   {
    //     model = model.OrderBy(r => r.Minutes).ToList();
    //   }
    //   return View(model);
    // }



  }
}

Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Flavor

<h4>Add a New Menu Item in this Flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorName)

    @Html.Label("Select Menu Item")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Create New Flavor", "Create")</p>
<p>@Html.ActionLink("Create New Menu Item", "Create", "Treats")</p>
<p>@Html.ActionLink("Back to Flavor Menu", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Flavor

<h4>Add a new Flavor</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.FlavorName)
    @Html.TextBoxFor(model => model.FlavorName)
    <input type="submit" value="Add new Flavor" />
}
<p>@Html.ActionLink("Show all Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>
@Html.HiddenFor(model => model.FlavorId)

@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Flavors", "Index")

Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Flavor;

<h2>Menu Items</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)</h3>

@if(@Model.Treats.Count == 0)
{
  <p>No menu items currently come in this flavor.</p>
}
else
{
  <ul>
  @foreach(var join in Model.Treats)
  {
    <li>@join.Treat.Name, $ @join.Treat.Price, @Html.ActionLink("See other flavors", "Details", "Treats", new {id = join.Treat.TreatId})</li>
  }
  </ul>
}
@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add A New Menu Item in this Flavor", "AddTreat", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Edit this Flavor", "Edit", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
  <br>
  <input type="submit" class="btn btn-default" value="Log out" />
}
else 
{
  <h4>@Html.ActionLink("Log in", "Login", "Account") to update menu with new Flavors and Menu Items.</h4>
}

<p>@Html.ActionLink("Back to Flavor List", "Index")</p>
<p>@Html.ActionLink("See All Menu Items", "Index", "Treats")</p>

Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Flavor


<h4>Edit this Flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorName)
    @Html.EditorFor(model => model.FlavorName)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Flavor List", "Index")</p>

Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetCakes.Models;
@model List<SweetCakes.Models.Flavor>;

<h2>All Flavors</h2>

@if (@Model.Count == 0)
{
  <h5>Everything is plain right now.</h5>
} 

@foreach (Flavor flav in Model)
{
  <ul>
    <li>@Html.ActionLink($"{flav.FlavorName}", "Details", new { id = flav.FlavorId })</li>
  </ul>
}
<br>
@if (User.Identity.IsAuthenticated)
  {
    <p>@Html.ActionLink("Create a New Flavor", "Create")</p>
  }
  else 
  {
    <h4>@Html.ActionLink("Log in", "Login", "Account") to create new flavors.</h4>
  }


<p>@Html.ActionLink("Home", "Index", "Home")</p>