Models/Treat.cs
using System.Collections.Generic;
using System;

namespace SweetCakes.Models
{
  public class Treat
  {
    public Treat()
    {
      this.Flavors = new List<FlavorTreat>();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }
    public int Price { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<FlavorTreat> Flavors { get; }
  }
}

Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using SweetCakes.Models;

namespace SweetCakes.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly SweetCakesContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, SweetCakesContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> Create(Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      _db.Flavors.Add(flav);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlav = _db.Flavors
          .Include(flav => flav.Treats)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    public ActionResult Edit(int id)
    {
      var thisFlav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> Edit(Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      _db.Entry(flav).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
      return View(thisFlav);
    }

    [HttpPost, ActionName("Delete")]
    [Authorize]
    public async Task<ActionResult> DeleteConfirmed(int id, Flavor flav)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flav.User = currentUser;
      var thisFlav = _db.Flavors.FirstOrDefault(f => f.FlavorId == id);
      _db.Flavors.Remove(thisFlav);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    [Authorize]
    public ActionResult AddFlavor(Flavor flav, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flav.FlavorId });
      }
      _db.Entry(flav).Collection(f => f.Treats).IsModified = true;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

Controllers/TreatController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using SweetCakes.Models;

namespace SweetCakes.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetCakesContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SweetCakesContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.Flavors)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddTag(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).Collection(t => t.Flavors).IsModified = true;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // [HttpGet("/search")]
    // public ActionResult Search(string search, string searchParam)
    // {

    //   if (!string.IsNullOrEmpty(search))
    //   {
    //     if (searchParam == "Tags")
    //     {
    //       var thisTag = _db.Tags
    //       .Include(tag => tag.Recipes)
    //       .ThenInclude(join => join.Recipe)
    //       .FirstOrDefault(tag => tag.Word == search);
    //       return View(thisTag.Recipes);

    //     }
    //     else if (searchParam == "Name")
    //     {
    //       var model = from r in _db.Recipes select r;
    //       model = model.Where(r => r.Name.Contains(search));
    //       List<Recipe> matches = model.ToList();
    //       return View(matches);
    //     }
    //     else
    //     {
    //       var model = from m in _db.Recipes select m;
    //       List<Recipe> allRecipes = new List<Recipe> { };
    //       allRecipes = model.ToList();
    //       return View(allRecipes);
    //     }
    //   }
    //   else
    //   {
    //     return RedirectToAction("Index");
    //   }
    // }
    // [HttpGet("/sort")]
    // public ActionResult Sort(string sortParam)
    // {
    //   List<Recipe> model = _db.Recipes.ToList();
    //   if (sortParam == "Rating")
    //   {
    //     model = model.OrderByDescending(r => r.Rating).ToList();
    //   }
    //   else
    //   {
    //     model = model.OrderBy(r => r.Minutes).ToList();
    //   }
    //   return View(model);
    // }



  }
}

Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using SweetCakes.Models;

namespace SweetCakes.Controllers
{
  public class TreatsController : Controller
  {
    private readonly SweetCakesContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SweetCakesContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.Flavors)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    [Authorize]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    [Authorize]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      _db.Entry(treat).Collection(t => t.Flavors).IsModified = true;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    [Authorize]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    [Authorize]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Treat

<h4>Add a New Flavor to this Menu Item: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select Flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Create New Flavor", "Flavors", "Create")</p>
<p>@Html.ActionLink("Back to Menu", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Treat

<h4>Add a new Treat to the Menu</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>

    @Html.LabelFor(model => model.Price)
    @Html.TextBoxFor(model => model.Price, new { @type = "number" })
    <br>

    @Html.Label("Add Flavors")
    @Html.DropDownList("FlavorId")
    <br>

    <input type="submit" value="Add new Treat" class="btn btn-default" />
}
<p>@Html.ActionLink("Show All Menu Items", "Index")</p>

<input type="submit" class="btn btn-default" value="Log out" />

Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Treat

<h2>Are you sure you want to delete this menu item?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Menu", "Index")

Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Treat

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>


  <ul> Flavors:
    <li>Plain</li>
    @foreach(var join in Model.Flavors)
    {
      <li>@join.Flavor.FlavorName</li>
    }
  </ul>
  <h4>Price: $@Html.DisplayFor(model => model.Price) </h4>

  @if (User.Identity.IsAuthenticated)
  {
    <p>@Html.ActionLink("Add A New Flavor for this Item", "AddFlavor", new { id = Model.TreatId })</p>
    <p>@Html.ActionLink("Edit this Menu Item", "Edit", new { id = Model.TreatId })</p>
    <p>@Html.ActionLink("Delete Menu Item", "Delete", new { id = Model.TreatId })</p>
    <br>
    <input type="submit" class="btn btn-default" value="Log out" />
  }
  else 
  {
    <h4>@Html.ActionLink("Log in", "Login", "Account") to update menu with new Items and Flavors.</h4>
  }
  
<br>

<p>@Html.ActionLink("Back to Menu", "Index")</p>

Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetCakes.Models.Treat

<h4>Edit this Menu Item: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.Label("Add Flavors")
    @Html.DropDownList("FlavorId")

    @Html.LabelFor(model => model.Price)
    @Html.EditorFor(model => model.Price, new { @type = "number"})

    <input type="submit" value="Save" />
}



<p>@Html.ActionLink("Back to Menu", "Index")</p>

Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetCakes.Models;
@model IEnumerable<SweetCakes.Models.Treat>

<h2>SweetCakes Menu</h2>

@* <form action="/sort" method = "get">
  @Html.RadioButton("sortParam", "Rating")
  <label for="sortParam">Sort by Rating</label>
  @Html.RadioButton("sortParam", "Minutes")
  <label for="sortParam">Sort by Prep Time</label>
  <button type="submit">Sort My RecipeBox</button>
</form> *@

@if (Model.Any())
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <h5>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</h5>
      @* <ul>
        <li>Rating: @Html.DisplayFor(modelRecipe => recipe.Rating)</li>
        <li>Prep Time: @Html.DisplayFor(modelRecipe => recipe.Minutes) minutes</li>
      </ul> *@
    }
  </ul>
} 
else
{
  <h3>Oops, we haven't updated our menu!</h3>
  @if (User.Identity.IsAuthenticated)
  {
    <p>@Html.ActionLink("Add New Menu Item", "Create")Create a new menu item</p>
  }
  else 
  {
    <h4>@Html.ActionLink("Log in", "Login", "Account")to create new menu items.</h4>
  }
}


<p>@Html.ActionLink("Home", "Index", "Home")</p>